### ISSUE TITLE
RichCodeNavIndexer is unable to locate executable file in Npgsql repo

### ISSUE THREAD

**Issue by vonzshik** [microsoft/RichCodeNavIndexer#128]
Hello!

A few years back RichCodeNavIndexer was added to Npgsql repo (npgsql/npgsql#3353) and it was working quite well for us.
Unfortunately, about 4 months ago it started failing with an error `Error: Unable to locate executable file: C:\Program. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.`.
Could you give us an idea if there is something wrong with our .yml config?

cc @roji

**Comment by noellelc** [comment]
We apologize for the inconvenience! We've been doing a little bit of refactoring on our side. We believe this error should be resolved, but please re-open this issue if you continue to see this error!

**Comment by vonzshik** [comment]
Yeah, we've re-enabled it and it seems to work. Thank you!
