### ISSUE TITLE
Error: Error: Unable to locate executable file: C:\Program. 

### ISSUE THREAD

**Issue by warrenbuckley** [microsoft/RichCodeNavIndexer#129]
## Error Logs

```
Run microsoft/RichCodeNavIndexer@v0.1
##[debug]Running on node.js v16.18.1
##[debug]Reading all inputs...
C:\ProgramData\Chocolatey\bin\nuget.exe sources add -name RichCodeNavFeed -source https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-buildservices@Local/nuget/v3/index.json -ConfigFile D:\a\_temp\RichCodeNav\nuget.config
Package source with Name: RichCodeNavFeed added successfully.
##[debug]exec tool: nuget
##[debug]arguments:
##[debug]  list
##[debug]  -pre
##[debug]  -source
##[debug]  RichCodeNavFeed
##[debug]  Microsoft.CodeIndex.ClientTool
##[debug]  -ConfigFile
##[debug]  D:\a\_temp\RichCodeNav\nuget.config
##[debug]Installing Microsoft.CodeIndex.ClientTool package version 0.1.2475-alpha...
Error: Error: Unable to locate executable file: C:\Program. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Run microsoft/RichCodeNavIndexer@v0.1
```

## GitHub Action Run
Here is recently failing GitHub Action run
https://github.com/warrenbuckley/Compact-Log-Format-Viewer/actions/runs/3650606456/jobs/6166798507#step:7:38

**Comment by warrenbuckley** [comment]
Hopefully one of you lovely people can assist me with this
@NTaylorMullen @mohaimenhasan @noellelc

**Comment by noellelc** [comment]
Yes! Sorry about this--I'll deploy a new task later today that should address this! Some of the upstream tooling has changed.

**Comment by warrenbuckley** [comment]
@noellelc did you get this updated ?

**Comment by noellelc** [comment]
@warrenbuckley  -- yes, I deployed a new release yesterday afternoon; let me know if it's still giving you trouble!

**Comment by noellelc** [comment]
@warrenbuckley -- has this been resolved for you?

**Comment by warrenbuckley** [comment]
@noellelc that didn't last long before it's come back again...
https://github.com/warrenbuckley/Compact-Log-Format-Viewer/actions/workflows/richcodenav.yml

https://github.com/warrenbuckley/Compact-Log-Format-Viewer/actions/runs/3739174976/jobs/6346072220#step:7:37

**Comment by noellelc** [comment]
Sorry for the back and forth. Things should be resolved now. Re-open if that's not the case!
